"""table name change

Revision ID: 5789e4938b33
Revises: e1379e946af2
Create Date: 2026-01-09 00:11:33.638658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5789e4938b33'
down_revision = 'e1379e946af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash', new_column_name='password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password', new_column_name='password_hash')

    # ### end Alembic commands ###
